name: Deploy Docs

on:
  push:
    branches:
      - main 

permissions:
  contents: write 

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/docs  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build 

      - name: Create .nojekyll file
        run: touch storybook-static/.nojekyll

      - name: Deploy to GitHub Pages
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}